### ISSUE TITLE
框架的自动加载和Symfony\Polyfill\Php72等不兼容问题

### ISSUE THREAD

**Issue by wenjy** [phwoolcon/phwoolcon#8]
执行命令：
vendor/bin/update-phwoolcon-package-resource
报错信息：
Fatal error: Uncaught Error: Class 'Symfony\Polyfill\Php72\Php72' not found in /Users/jiangyi/www/rebuy_git/vendor/symfony/polyfill-php72/bootstrap.php:29 Stack trace:  /Users/jiangyi/www/rebuy_git/vendor/composer/autoload_phalcon_files.php(3): include() /Users/jiangyi/www/rebuy_git/vendor/phwoolcon/bootstrap/bootstrap/start.php(23): include('/Users/jiangyi/...') 2 /Users/jiangyi/www/rebuy_git/bootstrap/start.php(11): include('/Users/jiangyi/...') 3 /Users/jiangyi/www/rebuy_git/bootstrap/ci_start.php(6): include('/Users/jiangyi/...') 4 /Users/jiangyi/www/rebuy_git/index.php(8): include('/Users/jiangyi/...') 5 {main} thrown in /Users/jiangyi/www/rebuy_git/vendor/symfony/polyfill-php72/bootstrap.php on line 29

文件位置：
vendor/phwoolcon/bootstrap/bootstrap/start.php

**Comment by wenjy** [comment]
require "swiftmailer/swiftmailer": "~5.4|~6.0"
swiftmailer/swiftmailer:v6.2.0 require "symfony/polyfill-intl-idn": "^1.10","symfony/polyfill-intl-idn" require "symfony/polyfill-php72": "^1.9"

需要删掉依赖~6.0，require "swiftmailer/swiftmailer": "~5.4"？

**Comment by Fishdrowned** [comment]
已在 https://github.com/phwoolcon/bootstrap/commit/4663ad0c8428804f5c8f5f67509454414efa0ce7 中修复

**Comment by Fishdrowned** [comment]
到项目根目录先更新（`git pull`）一次
